//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KVB.RESTAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Mpesa_WebService_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService")]
    public partial class Mpesa_WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTransIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBusinessShortCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBillRefNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrgAccountBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetThirdPartyTransIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMSISDNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMiddleNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Mpesa_WebService() {
            this.Url = global::KVB.Properties.Settings.Default.KVB_RESTAPI_Mpesa_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTransIDCompletedEventHandler GetTransIDCompleted;
        
        /// <remarks/>
        public event GetTransTimeCompletedEventHandler GetTransTimeCompleted;
        
        /// <remarks/>
        public event GetTransAmountCompletedEventHandler GetTransAmountCompleted;
        
        /// <remarks/>
        public event GetBusinessShortCodeCompletedEventHandler GetBusinessShortCodeCompleted;
        
        /// <remarks/>
        public event GetBillRefNumberCompletedEventHandler GetBillRefNumberCompleted;
        
        /// <remarks/>
        public event GetInvoiceNumberCompletedEventHandler GetInvoiceNumberCompleted;
        
        /// <remarks/>
        public event GetOrgAccountBalanceCompletedEventHandler GetOrgAccountBalanceCompleted;
        
        /// <remarks/>
        public event GetThirdPartyTransIDCompletedEventHandler GetThirdPartyTransIDCompleted;
        
        /// <remarks/>
        public event GetMSISDNCompletedEventHandler GetMSISDNCompleted;
        
        /// <remarks/>
        public event GetFirstNameCompletedEventHandler GetFirstNameCompleted;
        
        /// <remarks/>
        public event GetMiddleNameCompletedEventHandler GetMiddleNameCompleted;
        
        /// <remarks/>
        public event GetLastNameCompletedEventHandler GetLastNameCompleted;
        
        /// <remarks/>
        public event GetRequestsCompletedEventHandler GetRequestsCompleted;
        
        /// <remarks/>
        public event SaveTransactionCompletedEventHandler SaveTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetTransID", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetTransID_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetTransID(string transactionId) {
            object[] results = this.Invoke("GetTransID", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransIDAsync(string transactionId) {
            this.GetTransIDAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetTransIDAsync(string transactionId, object userState) {
            if ((this.GetTransIDOperationCompleted == null)) {
                this.GetTransIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransIDOperationCompleted);
            }
            this.InvokeAsync("GetTransID", new object[] {
                        transactionId}, this.GetTransIDOperationCompleted, userState);
        }
        
        private void OnGetTransIDOperationCompleted(object arg) {
            if ((this.GetTransIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransIDCompleted(this, new GetTransIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetTransTime", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetTransTime_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetTransTime(string transactionId) {
            object[] results = this.Invoke("GetTransTime", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransTimeAsync(string transactionId) {
            this.GetTransTimeAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetTransTimeAsync(string transactionId, object userState) {
            if ((this.GetTransTimeOperationCompleted == null)) {
                this.GetTransTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransTimeOperationCompleted);
            }
            this.InvokeAsync("GetTransTime", new object[] {
                        transactionId}, this.GetTransTimeOperationCompleted, userState);
        }
        
        private void OnGetTransTimeOperationCompleted(object arg) {
            if ((this.GetTransTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransTimeCompleted(this, new GetTransTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetTransAmount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetTransAmount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal GetTransAmount(string transactionId) {
            object[] results = this.Invoke("GetTransAmount", new object[] {
                        transactionId});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransAmountAsync(string transactionId) {
            this.GetTransAmountAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetTransAmountAsync(string transactionId, object userState) {
            if ((this.GetTransAmountOperationCompleted == null)) {
                this.GetTransAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransAmountOperationCompleted);
            }
            this.InvokeAsync("GetTransAmount", new object[] {
                        transactionId}, this.GetTransAmountOperationCompleted, userState);
        }
        
        private void OnGetTransAmountOperationCompleted(object arg) {
            if ((this.GetTransAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransAmountCompleted(this, new GetTransAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetBusinessShortCode", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetBusinessShortCode_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetBusinessShortCode(string transactionId) {
            object[] results = this.Invoke("GetBusinessShortCode", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBusinessShortCodeAsync(string transactionId) {
            this.GetBusinessShortCodeAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetBusinessShortCodeAsync(string transactionId, object userState) {
            if ((this.GetBusinessShortCodeOperationCompleted == null)) {
                this.GetBusinessShortCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusinessShortCodeOperationCompleted);
            }
            this.InvokeAsync("GetBusinessShortCode", new object[] {
                        transactionId}, this.GetBusinessShortCodeOperationCompleted, userState);
        }
        
        private void OnGetBusinessShortCodeOperationCompleted(object arg) {
            if ((this.GetBusinessShortCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusinessShortCodeCompleted(this, new GetBusinessShortCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetBillRefNumber", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetBillRefNumber_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetBillRefNumber(string transactionId) {
            object[] results = this.Invoke("GetBillRefNumber", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBillRefNumberAsync(string transactionId) {
            this.GetBillRefNumberAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetBillRefNumberAsync(string transactionId, object userState) {
            if ((this.GetBillRefNumberOperationCompleted == null)) {
                this.GetBillRefNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBillRefNumberOperationCompleted);
            }
            this.InvokeAsync("GetBillRefNumber", new object[] {
                        transactionId}, this.GetBillRefNumberOperationCompleted, userState);
        }
        
        private void OnGetBillRefNumberOperationCompleted(object arg) {
            if ((this.GetBillRefNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBillRefNumberCompleted(this, new GetBillRefNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetInvoiceNumber", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetInvoiceNumber_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetInvoiceNumber(string transactionId) {
            object[] results = this.Invoke("GetInvoiceNumber", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceNumberAsync(string transactionId) {
            this.GetInvoiceNumberAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetInvoiceNumberAsync(string transactionId, object userState) {
            if ((this.GetInvoiceNumberOperationCompleted == null)) {
                this.GetInvoiceNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceNumberOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceNumber", new object[] {
                        transactionId}, this.GetInvoiceNumberOperationCompleted, userState);
        }
        
        private void OnGetInvoiceNumberOperationCompleted(object arg) {
            if ((this.GetInvoiceNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceNumberCompleted(this, new GetInvoiceNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetOrgAccountBalance", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetOrgAccountBalance_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal GetOrgAccountBalance(string transactionId) {
            object[] results = this.Invoke("GetOrgAccountBalance", new object[] {
                        transactionId});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrgAccountBalanceAsync(string transactionId) {
            this.GetOrgAccountBalanceAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetOrgAccountBalanceAsync(string transactionId, object userState) {
            if ((this.GetOrgAccountBalanceOperationCompleted == null)) {
                this.GetOrgAccountBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrgAccountBalanceOperationCompleted);
            }
            this.InvokeAsync("GetOrgAccountBalance", new object[] {
                        transactionId}, this.GetOrgAccountBalanceOperationCompleted, userState);
        }
        
        private void OnGetOrgAccountBalanceOperationCompleted(object arg) {
            if ((this.GetOrgAccountBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrgAccountBalanceCompleted(this, new GetOrgAccountBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetThirdPartyTransID", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetThirdPartyTransID_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetThirdPartyTransID(string transactionId) {
            object[] results = this.Invoke("GetThirdPartyTransID", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetThirdPartyTransIDAsync(string transactionId) {
            this.GetThirdPartyTransIDAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetThirdPartyTransIDAsync(string transactionId, object userState) {
            if ((this.GetThirdPartyTransIDOperationCompleted == null)) {
                this.GetThirdPartyTransIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetThirdPartyTransIDOperationCompleted);
            }
            this.InvokeAsync("GetThirdPartyTransID", new object[] {
                        transactionId}, this.GetThirdPartyTransIDOperationCompleted, userState);
        }
        
        private void OnGetThirdPartyTransIDOperationCompleted(object arg) {
            if ((this.GetThirdPartyTransIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetThirdPartyTransIDCompleted(this, new GetThirdPartyTransIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetMSISDN", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetMSISDN_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetMSISDN(string transactionId) {
            object[] results = this.Invoke("GetMSISDN", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMSISDNAsync(string transactionId) {
            this.GetMSISDNAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetMSISDNAsync(string transactionId, object userState) {
            if ((this.GetMSISDNOperationCompleted == null)) {
                this.GetMSISDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMSISDNOperationCompleted);
            }
            this.InvokeAsync("GetMSISDN", new object[] {
                        transactionId}, this.GetMSISDNOperationCompleted, userState);
        }
        
        private void OnGetMSISDNOperationCompleted(object arg) {
            if ((this.GetMSISDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMSISDNCompleted(this, new GetMSISDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetFirstName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetFirstName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetFirstName(string transactionId) {
            object[] results = this.Invoke("GetFirstName", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstNameAsync(string transactionId) {
            this.GetFirstNameAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetFirstNameAsync(string transactionId, object userState) {
            if ((this.GetFirstNameOperationCompleted == null)) {
                this.GetFirstNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstNameOperationCompleted);
            }
            this.InvokeAsync("GetFirstName", new object[] {
                        transactionId}, this.GetFirstNameOperationCompleted, userState);
        }
        
        private void OnGetFirstNameOperationCompleted(object arg) {
            if ((this.GetFirstNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstNameCompleted(this, new GetFirstNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetMiddleName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetMiddleName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetMiddleName(string transactionId) {
            object[] results = this.Invoke("GetMiddleName", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMiddleNameAsync(string transactionId) {
            this.GetMiddleNameAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetMiddleNameAsync(string transactionId, object userState) {
            if ((this.GetMiddleNameOperationCompleted == null)) {
                this.GetMiddleNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMiddleNameOperationCompleted);
            }
            this.InvokeAsync("GetMiddleName", new object[] {
                        transactionId}, this.GetMiddleNameOperationCompleted, userState);
        }
        
        private void OnGetMiddleNameOperationCompleted(object arg) {
            if ((this.GetMiddleNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMiddleNameCompleted(this, new GetMiddleNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetLastName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetLastName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetLastName(string transactionId) {
            object[] results = this.Invoke("GetLastName", new object[] {
                        transactionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastNameAsync(string transactionId) {
            this.GetLastNameAsync(transactionId, null);
        }
        
        /// <remarks/>
        public void GetLastNameAsync(string transactionId, object userState) {
            if ((this.GetLastNameOperationCompleted == null)) {
                this.GetLastNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastNameOperationCompleted);
            }
            this.InvokeAsync("GetLastName", new object[] {
                        transactionId}, this.GetLastNameOperationCompleted, userState);
        }
        
        private void OnGetLastNameOperationCompleted(object arg) {
            if ((this.GetLastNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastNameCompleted(this, new GetLastNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:GetRequests", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="GetRequests_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetRequests(string transactionid) {
            object[] results = this.Invoke("GetRequests", new object[] {
                        transactionid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRequestsAsync(string transactionid) {
            this.GetRequestsAsync(transactionid, null);
        }
        
        /// <remarks/>
        public void GetRequestsAsync(string transactionid, object userState) {
            if ((this.GetRequestsOperationCompleted == null)) {
                this.GetRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequestsOperationCompleted);
            }
            this.InvokeAsync("GetRequests", new object[] {
                        transactionid}, this.GetRequestsOperationCompleted, userState);
        }
        
        private void OnGetRequestsOperationCompleted(object arg) {
            if ((this.GetRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequestsCompleted(this, new GetRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService:SaveTransaction", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", ResponseElementName="SaveTransaction_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mpesa_WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string SaveTransaction(string transID, string transactionType, string transTime, decimal transAmount, string businessShortCode, string billRefNumber, string invoiceNumber, decimal orgAccountBalance, string thirdPartyTransID, string mSISDN, string firstName, string middleName, string lastName, string action) {
            object[] results = this.Invoke("SaveTransaction", new object[] {
                        transID,
                        transactionType,
                        transTime,
                        transAmount,
                        businessShortCode,
                        billRefNumber,
                        invoiceNumber,
                        orgAccountBalance,
                        thirdPartyTransID,
                        mSISDN,
                        firstName,
                        middleName,
                        lastName,
                        action});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveTransactionAsync(string transID, string transactionType, string transTime, decimal transAmount, string businessShortCode, string billRefNumber, string invoiceNumber, decimal orgAccountBalance, string thirdPartyTransID, string mSISDN, string firstName, string middleName, string lastName, string action) {
            this.SaveTransactionAsync(transID, transactionType, transTime, transAmount, businessShortCode, billRefNumber, invoiceNumber, orgAccountBalance, thirdPartyTransID, mSISDN, firstName, middleName, lastName, action, null);
        }
        
        /// <remarks/>
        public void SaveTransactionAsync(string transID, string transactionType, string transTime, decimal transAmount, string businessShortCode, string billRefNumber, string invoiceNumber, decimal orgAccountBalance, string thirdPartyTransID, string mSISDN, string firstName, string middleName, string lastName, string action, object userState) {
            if ((this.SaveTransactionOperationCompleted == null)) {
                this.SaveTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveTransactionOperationCompleted);
            }
            this.InvokeAsync("SaveTransaction", new object[] {
                        transID,
                        transactionType,
                        transTime,
                        transAmount,
                        businessShortCode,
                        billRefNumber,
                        invoiceNumber,
                        orgAccountBalance,
                        thirdPartyTransID,
                        mSISDN,
                        firstName,
                        middleName,
                        lastName,
                        action}, this.SaveTransactionOperationCompleted, userState);
        }
        
        private void OnSaveTransactionOperationCompleted(object arg) {
            if ((this.SaveTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveTransactionCompleted(this, new SaveTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTransIDCompletedEventHandler(object sender, GetTransIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTransTimeCompletedEventHandler(object sender, GetTransTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTransAmountCompletedEventHandler(object sender, GetTransAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBusinessShortCodeCompletedEventHandler(object sender, GetBusinessShortCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusinessShortCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBusinessShortCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBillRefNumberCompletedEventHandler(object sender, GetBillRefNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBillRefNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBillRefNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInvoiceNumberCompletedEventHandler(object sender, GetInvoiceNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOrgAccountBalanceCompletedEventHandler(object sender, GetOrgAccountBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrgAccountBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrgAccountBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetThirdPartyTransIDCompletedEventHandler(object sender, GetThirdPartyTransIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetThirdPartyTransIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetThirdPartyTransIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMSISDNCompletedEventHandler(object sender, GetMSISDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMSISDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMSISDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFirstNameCompletedEventHandler(object sender, GetFirstNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMiddleNameCompletedEventHandler(object sender, GetMiddleNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMiddleNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMiddleNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetLastNameCompletedEventHandler(object sender, GetLastNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetRequestsCompletedEventHandler(object sender, GetRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SaveTransactionCompletedEventHandler(object sender, SaveTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591